### ISSUE TITLE
Crashes when loaded with Lithium

### ISSUE THREAD

**Issue by FewerFlaws** [Fox2Code/FabricZero#14]
When Minecraft 1.16.5 is loaded with Fabric API, Fabric Zero, and Lithium the game crashes on startup:
```
MultiMC version: 0.6.11-1430


Minecraft folder is:
E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/1- Fixes and Tools/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_271, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/1- Fixes and Tools/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader/0.11.1/fabric-loader-0.11.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] advdebug-2.2.0.jar (disabled)
  [❌] amecs-1.3.3+mc.1.16.3.jar (disabled)
  [❌] antighost-1.16.4-fabric0.25.1-1.1.3.jar (disabled)
  [❌] autoconfig1u-3.3.1.jar (disabled)
  [❌] blame-1.16.4-2.4.0.jar (disabled)
  [❌] cloth-api-1.4.9.jar (disabled)
  [❌] config-2-4.8.3.jar (disabled)
  [❌] DisableCustomWorldsAdvice-1.2.jar (disabled)
  [❌] dynamic-fps-2.0.0.jar (disabled)
  [✔️] fabric-api-0.29.4+1.16
  [❌] fabric-chunkpregen-0.3.3.jar (disabled)
  [✔️] fabriczero-0.2.0
  [❌] fastbench-2.3.jar (disabled)
  [❌] fastfurnace-2.3.jar (disabled)
  [❌] fatxporbs-0.0.9+1.16.4.jar (disabled)
  [❌] ice-boat-nerf-1.0.4+MC1.16.2-1.16.5.jar (disabled)
  [❌] item-model-fix-1.0.0.jar (disabled)
  [❌] juke-fix-1.0.0.jar (disabled)
  [❌] lazydfu-0.1.1.jar (disabled)
  [✔️] lithium-fabric-mc1.16.5-0.6.1
  [❌] modmenu-1.14.15.jar (disabled)
  [❌] mousewheelie-1.6.3+mc1.16.4.jar (disabled)
  [❌] phosphor-fabric-mc1.16.3-0.7.0+build.10.jar (disabled)
  [❌] randompatches-2.2.0-fabric.jar (disabled)
  [❌] RoughlyEnoughItems-5.8.11.jar (disabled)
  [❌] sodium-fabric-mc1.16.3-0.1.0.jar (disabled)
  [❌] spark-fabric.jar (disabled)
  [❌] tooltipfix-1.0.2-1.16.1.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/1- Fixes and Tools/.minecraft --assetsDir E:/minecraft/multiMC/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 1280 x 720

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 14652


Using onesix launcher.

[23:37:23] [main/INFO]: Loading for game Minecraft 1.16.5
[23:37:23] [main/INFO]: [FabricLoader] Loading 47 mods: fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-renderer-api-v1@0.4.1+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabric-command-api-v1@1.0.10+ca58154a7d, fabricloader@0.11.1, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabriczero@0.2.0, fabric-containers-v0@0.1.10+ca58154a7d, lithium@0.6.1, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.29.4+1.16, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d
[23:37:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[23:37:24] [main/INFO]: Loaded configuration file for Lithium: 66 options available, 0 override(s) found
[23:37:24] [main/INFO]: FabricZero: Loaded!
[23:37:24] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[23:37:30] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:37:31] [main/INFO]: Setting user: Josheva
[23:37:32] [main/INFO]: [Indigo] Registering Indigo renderer!
[23:37:32] [Async Class PreLoader/INFO]: Preloading classes...
[23:37:32] [main/INFO]: [STDOUT]: E:\minecraft\multiMC\mmc-stable-win32\MultiMC\libraries\com\mojang\minecraft\1.16.5\minecraft-1.16.5-client.jar
[23:37:32] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[23:37:36] [Async Class PreLoader/INFO]: Preloaded 5445 classes!
---- Minecraft Crash Report ----
// There are four lights!

Time: 24/01/21 11:37 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraft.class_3532.method_15362(class_3532.java:946)
	at net.minecraft.class_570.method_24185(class_570.java:120)
	at net.minecraft.class_570.<init>(class_570.java:60)
	at net.minecraft.class_907.<init>(class_907.java:32)
	at net.minecraft.class_893.<init>(class_893.java:12)
	at net.minecraft.class_898.method_23167(class_898.java:98)
	at net.minecraft.class_898.<init>(class_898.java:192)
	at net.minecraft.class_310.<init>(class_310.java:527)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalArgumentException: LUT error at index 16385 (expected: -1.917476E-4, found: 1.917476E-4)
	at me.jellysquid.mods.lithium.common.util.math.CompactSineLUT.<clinit>(CompactSineLUT.java:48)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_3532.method_15362(class_3532.java:946)
	at net.minecraft.class_570.method_24185(class_570.java:120)
	at net.minecraft.class_570.<init>(class_570.java:60)
	at net.minecraft.class_907.<init>(class_907.java:32)
	at net.minecraft.class_893.<init>(class_893.java:12)
	at net.minecraft.class_898.method_23167(class_898.java:98)
	at net.minecraft.class_898.<init>(class_898.java:192)
	at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2982688496 bytes (2844 MB) / 4173856768 bytes (3980 MB) up to 4173856768 bytes (3980 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		fabric: Fabric API 0.29.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fabriczero: Fabric Zero 0.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lithium: Lithium 0.6.1
		minecraft: Minecraft 1.16.5
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
#@!@# Game crashed! Crash report saved to: #@!@# E:\minecraft\multiMC\mmc-stable-win32\MultiMC\instances\1- Fixes and Tools\.minecraft\crash-reports\crash-2021-01-24_23.37.36-client.txt
Process exited with code -1.
```

**Comment by Fox2Code** [comment]
Fixed in 0.2.1
